#MySQL Local
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wepik
    username: root
    password: '0000'

  jpa:
    hibernate:
      ddl-auto: create
cloud:
  aws:
    s3:
      bucket: wepik-s3-bucket
    credentials:
      access-key: AKIA2UC3AZLTGA2TKPZH  # CLOUD_AWS_CREDENTIALS_ACCESS_KEY
      secret-key: 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  # CLOUD_AWS_CREDENTIALS_SECRET_KEY
    region:
      static: ap-northeast-2

server:
  port: 80